package com.aug.triton.db.remoteentity;
// Generated 3-Nov-2011 2:30:54 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.Set;

/**
 * FinalDetectionResult generated by hbm2java
 */
public class FinalDetectionResult  implements java.io.Serializable {


     private long id;
     private Date sampleTime;
     private Boolean combinedAnomaly;
     private Float combinedConfidence;
//     private Set sensorReadingGroups;
//     private Set spectraDetections;     

    public FinalDetectionResult() {
    }

	
    public FinalDetectionResult(long id, Date sampleTime) {
        this.id = id;
        this.sampleTime = sampleTime;
    }
    
    public FinalDetectionResult(long id, Date sampleTime, Boolean combinedAnomaly, Float combinedConfidence) {
       this.id = id;
       this.sampleTime = sampleTime;
       this.combinedAnomaly = combinedAnomaly;
       this.combinedConfidence = combinedConfidence;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Date getSampleTime() {
        return this.sampleTime;
    }
    
    public void setSampleTime(Date sampleTime) {
        this.sampleTime = sampleTime;
    }
    public Boolean getCombinedAnomaly() {
        return this.combinedAnomaly;
    }
    
    public void setCombinedAnomaly(Boolean combinedAnomaly) {
        this.combinedAnomaly = combinedAnomaly;
    }
    public Float getCombinedConfidence() {
        return this.combinedConfidence;
    }
    
    public void setCombinedConfidence(Float combinedConfidence) {
        this.combinedConfidence = combinedConfidence;
    }

//    public Set getSensorReadingGroups() {
//        return this.sensorReadingGroups;
//    }
//
//    public void setSensorReadingGroups(Set sensorReadingGroups) {
//        this.sensorReadingGroups = sensorReadingGroups;
//    }
//    
//    public Set getSpectraDetections() {
//        return this.spectraDetections;
//    }
//    
//    public void setSpectraDetections (Set spectraDetections) {
//        this.spectraDetections = spectraDetections;
//    }
    
}


