package com.aug.triton.db.remoteentity;
// Generated 3-Nov-2011 2:30:54 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import java.sql.Timestamp;




/**
 * Sensor generated by hbm2java
 */
public class Sensor  implements java.io.Serializable {


     private short id;
     private String name;
     private String unit;
     private Double minValue;
     private Double maxValue;
     private Double tempAdjSlope;
     private Double extremeLower;
     private Double extremeUpper;
     private boolean needUpdate;
     private Timestamp lastUpdated;
     private Set sensorReadings = new HashSet(0);

    public Sensor() {
    }

	
    public Sensor(short id, String name) {
        this.id = id;
        this.name = name;
    }
    
    public Sensor(short id, String name, String unit, Double minValue, 
            Double maxValue, Double tempAdjSlope, Double extremeLower,
            Double extremeUppper, Set sensorReadings) {
       this.id = id;
       this.name = name;
       this.unit = unit;
       this.minValue = minValue;
       this.maxValue = maxValue;
       this.tempAdjSlope = tempAdjSlope;
       this.extremeLower = extremeLower;
       this.extremeUpper = extremeUppper;
       this.sensorReadings = sensorReadings;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Double getMinValue() {
        return this.minValue;
    }
    
    public void setMinValue(Double minValue) {
        this.minValue = minValue;
    }
    public Double getMaxValue() {
        return this.maxValue;
    }
    
    public void setMaxValue(Double maxValue) {
        this.maxValue = maxValue;
    }

    public Double getTempAdjSlope() {
        return this.tempAdjSlope;
    }
    
    public void setTempAdjSlope(Double tempAdjSlope) {
        this.tempAdjSlope = tempAdjSlope;
    }
    
    public Double getExtremeLower() {
        return this.extremeLower;
    }
    
    public void setExtremeLower(Double extremeLower) {
        this.extremeLower = extremeLower;
    }
    
    public Double getExtremeUpper() {
        return this.extremeUpper;
    }
    
    public void setExtremeUpper(Double extremeUpper) {
        this.extremeUpper = extremeUpper;
    }
    
    public Set getSensorReadings() {
        return this.sensorReadings;
    }

    public void setSensorReadings(Set sensorReadings) {
        this.sensorReadings = sensorReadings;
    }
    
    public boolean getNeedUpdate(){
        return this.needUpdate;
    }
    
    public void setNeedUpdate(boolean needUpdate){
        this.needUpdate = needUpdate;
    }
    
    public Timestamp getLastUpdated(){
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Timestamp lastUpdated){
        this.lastUpdated = lastUpdated;
    }
}


