package com.aug.triton.db.remoteentity;
// Generated 3-Nov-2011 2:30:54 PM by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * SpectraDetection generated by hbm2java
 */
public class SpectraDetection  implements java.io.Serializable {


     private long id;
     private Timestamp sampleTime;
     private Boolean anomaly;
     private Float confidence;
     private TapRef tapRef;
     private Set spectraReadings = new HashSet(0);
     private Set potentialConts = new HashSet(0);
     private Set finalDetectionResults = new HashSet(0);

    public SpectraDetection() {
    }

	
    public SpectraDetection(long id, Timestamp sampleTime) {
        this.id = id;
        this.sampleTime = sampleTime;
    }
    public SpectraDetection(long id, Timestamp sampleTime, Boolean anomaly, Float confidence, TapRef tapRef, Set spectraReadings, Set potentialConts, Set finalDetectionResults) {
       this.id = id;
       this.sampleTime = sampleTime;
       this.anomaly = anomaly;
       this.confidence = confidence;
       this.tapRef = tapRef;
       this.spectraReadings = spectraReadings;
       this.potentialConts = potentialConts;
       this.finalDetectionResults = finalDetectionResults;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Timestamp getSampleTime() {
        return this.sampleTime;
    }
    
    public void setSampleTime(Timestamp sampleTime) {
        this.sampleTime = sampleTime;
    }
    public Boolean getAnomaly() {
        return this.anomaly;
    }
    
    public void setAnomaly(Boolean anomaly) {
        this.anomaly = anomaly;
    }
    public Float getConfidence() {
        return this.confidence;
    }
    
    public void setConfidence(Float confidence) {
        this.confidence = confidence;
    }
    public TapRef getTapRef() {
        return this.tapRef;
    }
    
    public void setTapRef(TapRef tapRef) {
        this.tapRef = tapRef;
    }
    public Set getSpectraReadings() {
        return this.spectraReadings;
    }
    
    public void setSpectraReadings(Set spectraReadings) {
        this.spectraReadings = spectraReadings;
    }
    public Set getPotentialConts() {
        return this.potentialConts;
    }
    
    public void setPotentialConts(Set potentialConts) {
        this.potentialConts = potentialConts;
    }
    public Set getFinalDetectionResults() {
        return this.finalDetectionResults;
    }
    
    public void setFinalDetectionResults(Set finalDetectionResults) {
        this.finalDetectionResults = finalDetectionResults;
    }

}


