package com.aug.triton.db.remoteentity;
// Generated 3-Nov-2011 2:30:54 PM by Hibernate Tools 3.2.1.GA



/**
 * TapRefData generated by hbm2java
 */
public class TapRefData  implements java.io.Serializable {


     private long id;
     private TapRef tapRef;
     private float wavelength;
     private float absorption;

    public TapRefData() {
    }

    public TapRefData(long id, TapRef tapRef, float wavelength, float absorption) {
       this.id = id;
       this.tapRef = tapRef;
       this.wavelength = wavelength;
       this.absorption = absorption;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public TapRef getTapRef() {
        return this.tapRef;
    }
    
    public void setTapRef(TapRef tapRef) {
        this.tapRef = tapRef;
    }
    public float getWavelength() {
        return this.wavelength;
    }
    
    public void setWavelength(float wavelength) {
        this.wavelength = wavelength;
    }
    public float getAbsorption() {
        return this.absorption;
    }
    
    public void setAbsorption(float absorption) {
        this.absorption = absorption;
    }




}


