/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aug.triton.db.remoteentity;

import java.sql.Timestamp;

/**
 * SensorReading generated by hbm2java
 */
public class TocReading  implements java.io.Serializable {


     private long id;
     private Boolean isDetected;
     private Boolean isUploaded;
     private Double confidence;
     private Double tocReading;
     private Double icReading;
     private Timestamp sampleTime;     

    public TocReading() {
    }

	
    public TocReading(long id) {
        this.id = id;
    }

    public TocReading(long id, Boolean isDetected, Double confidence, Boolean isUploaded, Double tocReading, Double icReading, Timestamp sampleTime) {
       this.id = id;
       this.isDetected = isDetected;
       this.confidence = confidence;
       this.tocReading = tocReading;
       this.icReading = icReading;
       this.isUploaded = isUploaded;
    }
       
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    public Boolean getIsDetected() {
        return this.isDetected;
    }
    
    public void setIsDetected(Boolean isDetected) {
        this.isDetected = isDetected;
    }
    public Double getConfidence() {
        return this.confidence;
    }
    
    public void setConfidence(Double confidence) {
        this.confidence = confidence;
    }
    public Double getTocReading() {
        return this.tocReading;
    }
    
    public void setTocReading(Double tocReading) {
        this.tocReading = tocReading;
    }

    public Double getIcReading() {
        return this.icReading;
    }

    public void setIcReading(Double icReading) {
        this.icReading = icReading;
    }

    public Boolean getIsUploaded(){
        return this.isUploaded;
    }

    public void setIsUploaded(Boolean isUploaded){
        this.isUploaded = isUploaded;
    }

    public Timestamp getSampleTime() {
        return this.sampleTime;
    }
    
    public void setSampleTime(Timestamp sampleTime) {
        this.sampleTime = sampleTime;
    }
    
}
